image: golang:1.12.7

before_script:
  - go get -u -v github.com/Permaweb/Host
  - go clean

build:
  stage: build
  script:
    - go get -u -v github.com/GeertJohan/go.rice/rice
    - rice embed-go
    - go build

test:
  stage: test
  script:
    - go test -v -cover ./...

after_script:
  - go clean
