name: permaweb-host
title: Permaweb Host
base: core18
version: git
summary: Throws a Git repo to IPNS
description: |
  Permaweb Host exposes a web interface and an API to add Git repos to IPNS.
  This interface is not protected. Ideally, if you want to sell its services,
  you should create your own web interface with user authentication and a payment gateway.
type: app
confinement: devmode
license: MIT
grade: devel
parts:
  permaweb-host:
    build-packages:
      - gcc
      - git
    build-snaps:
      - ipfs/latest/edge
      - node/12/stable
    override-build: |
      sudo npm install --global hogan.js
      npx hulk ./web/mustache/*.html --outputdir ./web/templates/

      go get -u github.com/GeertJohan/go.rice/rice
      ~/go/bin/rice embed-go

      ./scripts/ipfs.sh

      snapcraftctl build
    source: .
#    stage-snaps:
#      - ipfs/edge
#      - ipfs-cluster/edge
    plugin: go
    go-channel: latest/stable
    go-importpath: github.com/Permaweb/Host
apps:
  permaweb-host:
    command: bin/Host